const R={"Beetle Scuttle":["Breach","Increase Armor","Protection","Vitality"],"Blessed Thistle":["Restore Stamina","Increase Weapon Power","Ravage Health","Speed"],"Blue Entoloma":["Ravage Magicka","Cowardice","Restore Health","Invisible"],"Bugloss":["Increase Spell Resist","Restore Health","Cowardice","Restore Magicka"],"Butterfly Wing":["Restore Health","Uncertainty","Lingering Health","Vitality"],"Chaurus Egg":["Timidity","Ravage Magicka","Restore Stamina","Detection"],"Clam Gall":["Increase Spell Resist","Hindrance","Vulnerability","Defile"],"Columbine":["Restore Health","Restore Magicka","Restore Stamina","Unstoppable"],"Corn Flower":["Restore Magicka","Increase Spell Power","Ravage Health","Detection"],"Crimson Nirnroot":["Timidity","Critical","Gradual Ravage Health","Restore Health"],"Dragon's Bile":["Heroism","Vulnerability","Invisible","Vitality"],"Dragon's Blood":["Lingering Health","Restore Stamina","Heroism","Defile"],"Dragon Rheum":["Restore Magicka","Heroism","Enervation","Speed"],"Dragonthorn":["Increase Weapon Power","Restore Stamina","Fracture","Critical"],"Emetic Russula":["Ravage Health","Ravage Magicka","Ravage Stamina","Entrapment"],"Fleshfly Larva":["Ravage Stamina","Gradual Ravage Health","Vulnerability","Vitality"],"Imp Stool":["Maim","Ravage Stamina","Increase Armor","Enervation"],"Lady's Smock":["Increase Spell Power","Restore Magicka","Breach","Critical"],"Luminous Russula":["Ravage Stamina","Maim","Restore Health","Hindrance"],"Mountain Flower":["Increase Armor","Restore Health","Maim","Restore Stamina"],"Mudcrab Chitin":["Increase Spell Resist","Protection","Increase Armor","Defile"],"Namira's Rot":["Critical","Speed","Invisible","Unstoppable"],"Nightshade":["Ravage Health","Gradual Ravage Health","Protection","Defile"],"Nirnroot":["Ravage Health","Uncertainty","Enervation","Invisible"],"Powdered Mother of Pearl":["Lingering Health","Speed","Vitality","Protection"],"Scrib Jelly":["Ravage Magicka","Vulnerability","Speed","Lingering Health"],"Spider Egg":["Hindrance","Invisible","Lingering Health","Defile"],"Stinkhorn":["Fracture","Ravage Health","Increase Weapon Power","Ravage Stamina"],"Torchbug Thorax":["Fracture","Enervation","Detection","Vitality"],"Vile Coagulant":["Timidity","Ravage Health","Restore Magicka","Protection"],"Violet Coprinus":["Breach","Ravage Health","Increase Spell Power","Ravage Magicka"],"Water Hyacinth":["Restore Health","Critical","Weapon Critical","Entrapment"],"White Cap":["Cowardice","Ravage Magicka","Increase Spell Resist","Detection"],"Wormwood":["Critical","Hindrance","Detection","Unstoppable"]};
const POTION_WATERS=["Natural Water","Clear Water","Pristine Water","Cleansed Water","Filtered Water","Purified Water","Cloud Mist","Star Dew","Lorkhan's Tears"];
const POISON_SOLVENTS=["Grease","Ichor","Slime","Gall","Terebinthine","Pitch-Bile","Tarblack","Night-Oil","Alkahest"];
const SAVE_KEY="TheAlchemistArchive_v1";let archive=loadArchive(),inventoryOnly=true,best=null,selectedEffects=[],history=JSON.parse(localStorage.TheAlchemistHistory_v1||"[]");
function initSolvents(){let s={};POTION_WATERS.concat(POISON_SOLVENTS).forEach(x=>s[x]={qty:0,reserve:20});return s}
function ensureProfileShape(){let p=profile();if(!p)return;if(!p.solvents)p.solvents=initSolvents();POTION_WATERS.concat(POISON_SOLVENTS).forEach(x=>{if(!p.solvents[x])p.solvents[x]={qty:0,reserve:20}});if(!p.favoriteRecipes)p.favoriteRecipes=[]}
function solventData(){ensureProfileShape();return profile().solvents}
function newProfile(name){let d={};for(const r in R)d[r]={learned:[false,false,false,false],qty:0,fav:false,reserve:20};return{id:"p_"+Date.now(),name:name||"Adventurer",created:new Date().toISOString(),lastOpen:new Date().toISOString(),data:d,solvents:initSolvents(),favoriteRecipes:[],session:{crafts:0,traits:0,complete:0},settings:{greeting:"normal"}}}
function loadArchive(){try{let a=JSON.parse(localStorage.getItem(SAVE_KEY));if(a&&a.profiles&&a.profiles.length)return a}catch(e){}return{version:"5.4.1",activeProfile:null,profiles:[],created:new Date().toISOString(),lastSaved:null}}
function profile(){return archive.profiles.find(p=>p.id===archive.activeProfile)}
function data(){return profile().data}
function session(){return profile().session}
function save(){archive.lastSaved=new Date().toISOString();let p=profile();if(p)p.lastOpen=new Date().toISOString();localStorage.setItem(SAVE_KEY,JSON.stringify(archive));render()}
function createFirstProfile(){let name=(profileName.value||"Adventurer").trim();let p=newProfile(name);archive.profiles.push(p);archive.activeProfile=p.id;save()}
function addProfile(){let name=(document.getElementById("newProfileName").value||"New Character").trim();let p=newProfile(name);archive.profiles.push(p);archive.activeProfile=p.id;document.getElementById("newProfileName").value="";save()}
function switchProfile(id){archive.activeProfile=id;save()}
function renameActiveProfile(){let p=profile();let box=document.getElementById("renameProfileName");let name=(box.value||"").trim();if(!name){alert("Enter a new archive name first.");return}p.name=name;box.value="";save()}
function deleteActiveProfile(){if(archive.profiles.length<=1){alert("Aldren must keep at least one archive.");return}let p=profile();if(!confirm("Delete the archive for "+p.name+"?"))return;archive.profiles=archive.profiles.filter(x=>x.id!==p.id);archive.activeProfile=archive.profiles[0].id;save()}
